<a href="https://colab.research.google.com/github/redidkfr/Demo/blob/main/pypypy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("nonsense")

nonsense


In [ ]:
!pip install torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 55.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 35.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 41.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━ 314.6/664.8 MB 7.9 MB/s eta 0:00:45
ERROR: Operation cancelled by user


In [ ]:
kanto = [34,43,78]
weights = [0.3,0.2,0.5]

In [ ]:
for x,v in zip(kanto,weights):
  print(x,v)

34 0.3
43 0.2
78 0.5


In [3]:
import numpy as np
kanto = np.array([73,67,63])
weights = np.array([0.5,0.2,0.3])
print(np.dot(kanto,weights))
## matrix vector multiplication allows for the dot product of each row or the matrix with the vector and the function is np.matmul() or np.dot()

68.8


In [7]:
np.ones([2,2,3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [11]:
np.random.rand(6)

array([0.90459214, 0.93671045, 0.74315279, 0.57464701, 0.65808989,
       0.56393199])

In [13]:
np.random.randn(2,3)

array([[ 0.1224835 ,  0.83727304, -1.8462079 ],
       [-0.94699447, -2.45414646, -0.97837792]])

In [16]:
np.full([2,3], 115)
#np.arrange(x,y,z) is like for loops saying start at x end at y and step z
#np.linspace()similar but step is number of elements spaced out evenly not space between

array([[115, 115, 115],
       [115, 115, 115]])